GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Buy cake"
}

###

DELETE http://localhost:3001/todo/delete/64193dfd0784acf3987a971d

###

PUT http://localhost:3001/todo/complete/641953c50abbcba45771853d